name: Breakout Game

on:
  schedule:
    - cron: "0 0 * * *" # 매일 자정 실행
  workflow_dispatch:     # 수동 실행 가능

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write    # 파일 쓰기 권한 명시
    steps:
      - uses: actions/checkout@v4
      
      - name: Generate Breakout Game
        uses: goms7/github-breakout@main
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          github_username: goms7

      - name: Commit and Push
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          # 생성된 파일이 'output' 폴더에 생기므로 이를 현재 폴더로 가져옵니다.
          mv output/*.svg . || true 
          git add .
          git commit -m "Update Breakout Game" || exit 0
          git push
